name: Build, Push, and Deploy to GKE

on:
  push:
    branches:
      - main  # マージ先のブランチを指定

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create service account key file
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > gcloud-service-key.json

    - name: Upload service account key file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: gcloud-service-key
        path: gcloud-service-key.json

    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
        echo "deb https://packages.cloud.google.com/apt gke-gcloud-auth-plugin main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Download service account key file
      uses: actions/download-artifact@v2
      with:
        name: gcloud-service-key
        path: .

    - name: Authenticate to Google Cloud
      run: |
        gcloud auth activate-service-account --key-file=gcloud-service-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/altx-deep-counter-mk-gcs-dirs/my-app:latest .

    - name: Push Docker image
      run: |
        docker push asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/altx-deep-counter-mk-gcs-dirs/my-app:latest

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/my-deployment my-container=asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/altx-deep-counter-mk-gcs-dirs/my-app:latest
