name: Build, Push, and Deploy to GKE

on:
  push:
    branches:
      - main  # マージ先のブランチを指定する。

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/altx-deep-counter-mk-gcs-dirs/my-app:latest .

    - name: Push Docker image
      run: |
        docker push asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/altx-deep-counter-mk-gcs-dirs/my-app:latest

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/my-deployment asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/altx-deep-counter-mk-gcs-dirs/my-app:latest
